"""
email_sender.py — Gmail SMTP, HTML, retry
"""
import time
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

logger = logging.getLogger(__name__)

DISCLAIMER = "⚠️ This alert is generated by an automated rule-based system for informational purposes only. It is NOT financial advice. Signals are based on configurable heuristics and may be wrong. Always do your own research before making any trading decisions. Past signal accuracy does not guarantee future results."


def build_html(coin, price, change_24h, volume, avg_volume, signal_info, price_details, news_top, onchain_events):
    emoji = signal_info.get("emoji", "")
    signal = signal_info.get("signal", "NEUTRAL")
    score = signal_info.get("composite_score", 0)
    color = signal_info.get("color", "#f5c518")
    rsi = signal_info.get("rsi")
    macd = signal_info.get("macd")
    w = signal_info.get("weights") or {}
    wp = w.get("price", 0)
    wn = w.get("news", 0)
    wo = w.get("onchain", 0)
    label_map = {
        "DUMP_WARNING": "DUMP WARNING — Consider Exiting",
        "BEARISH": "BEARISH — Caution / Watch",
        "NEUTRAL": "NEUTRAL — Hold / Monitor",
        "BULLISH": "BULLISH — Watch for Entry",
        "STRONG_BUY": "STRONG BUY — Entry Candidate",
    }
    label = label_map.get(signal, signal)
    rsi_str = f"{rsi:.1f}" if rsi is not None else "n/a"
    macd_str = f"{macd.get('direction','n/a')} (hist {macd.get('histogram',0):+.3f})" if macd else "n/a"
    vol_str = f"{volume:,.0f}" if volume else "n/a"
    avg_str = f"{avg_volume:,.0f}" if avg_volume else "n/a"
    news_rows = ""
    for n in (news_top or [])[:3]:
        title = n.get("title","")
        link = n.get("link","#")
        src = ",".join(n.get("sources", [n.get("source","")]))
        score_n = n.get("news_score", 0)
        news_rows += f"<tr><td><a href='{link}'>{title}</a> <small>({src})</small></td><td>{score_n:+.1f}</td></tr>"
    if not news_rows:
        news_rows = "<tr><td colspan='2'>No strong news triggers</td></tr>"
    onchain_rows = ""
    for e in (onchain_events or [])[:3]:
        onchain_rows += f"<tr><td>{e.get('title','')[:100]}</td><td>{e.get('score','')}</td></tr>"
    if not onchain_rows:
        onchain_rows = "<tr><td colspan='2'>No whale activity</td></tr>"

    html = f"""
<html><body style="font-family:Arial,sans-serif;background:#0f1115;color:#e6e6e6;padding:20px">
<div style="max-width:700px;margin:auto;background:#1a1d24;border-radius:12px;padding:24px;border-left:6px solid {color}">
<h2 style="margin:0;color:{color}">{emoji} {coin.upper()} — {label}</h2>
<p style="color:#aaa;margin:6px 0 12px 0">Composite score: <b>{score:+.2f}</b> &nbsp;|&nbsp; Weights price {wp:.2f} / news {wn:.2f} / onchain {wo:.2f}</p>

<div style="background:#242831;border-radius:8px;padding:14px;margin:14px 0">
<h3 style="margin:0 0 8px 0">Price</h3>
<table style="width:100%;font-size:14px">
<tr><td>Current</td><td><b>${price:,.2f}</b></td></tr>
<tr><td>24h change</td><td>{change_24h:+.2f}%</td></tr>
<tr><td>Volume vs avg</td><td>{vol_str} vs {avg_str}</td></tr>
<tr><td>RSI</td><td>{rsi_str}</td></tr>
<tr><td>MACD</td><td>{macd_str}</td></tr>
<tr><td>Triggers</td><td>{', '.join(price_details) if price_details else 'none'}</td></tr>
</table>
</div>

<div style="background:#242831;border-radius:8px;padding:14px;margin:14px 0">
<h3 style="margin:0 0 8px 0">Top News</h3>
<table style="width:100%;font-size:13px">{news_rows}</table>
</div>

<div style="background:#242831;border-radius:8px;padding:14px;margin:14px 0">
<h3 style="margin:0 0 8px 0">On-Chain</h3>
<table style="width:100%;font-size:13px">{onchain_rows}</table>
</div>

<p style="font-size:12px;color:#888;margin-top:18px">{DISCLAIMER}</p>
<p style="font-size:11px;color:#666">Generated {signal_info.get('timestamp','')} — Next check in {signal_info.get('poll_interval',30)}m</p>
</div>
</body></html>
"""
    return html


def send_email(gmail_user, app_password, to_email, subject, html_body):
    if not gmail_user or not app_password or not to_email:
        logger.warning("Email credentials missing — skip")
        return False
    msg = MIMEMultipart("alternative")
    msg["From"] = gmail_user
    msg["To"] = to_email
    msg["Subject"] = subject
    msg.attach(MIMEText(html_body, "html"))
    # plain fallback
    msg.attach(MIMEText("HTML email — view in HTML-capable client.", "plain"))
    for attempt in range(2):
        try:
            with smtplib.SMTP("smtp.gmail.com", 587, timeout=20) as server:
                server.starttls()
                server.login(gmail_user, app_password)
                server.sendmail(gmail_user, to_email, msg.as_string())
            logger.info(f"Email sent to {to_email}: {subject}")
            return True
        except Exception as e:
            logger.warning(f"Email attempt {attempt+1} fail: {e}")
            if attempt == 0:
                time.sleep(30)
    return False
