#!/usr/bin/env python3
"""
main.py — orchestrator, handles --dry-run, secrets, cooldown, dashboard, state persistence.
"""
import os
import sys
import argparse
import logging
import random
import time
from datetime import datetime, timezone
from pathlib import Path

# Ensure src is on path
sys.path.insert(0, str(Path(__file__).resolve().parent))

import yaml
from dotenv import load_dotenv

from state.state_manager import StateManager
from fetchers.price_fetcher import fetch_prices
from fetchers.news_fetcher import fetch_news
from fetchers.onchain_fetcher import fetch_onchain, aggregate_onchain_score
from signals.price_signals import evaluate_price
from signals.news_signals import evaluate_news
from signals.onchain_signals import evaluate_onchain
from signals.signal_engine import evaluate as engine_evaluate, meets_min_signal, passes_quality_gate
from alerts.telegram_sender import send_telegram, format_telegram
from alerts.email_sender import send_email, build_html
from dashboard.generate_dashboard import generate_dashboard
from utils.startup_check import run_startup_check

# Load .env from project root (trading news/.env) — works regardless of cwd (local vs GitHub Actions)
try:
    _proj_root = Path(__file__).resolve().parent.parent
    load_dotenv(dotenv_path=_proj_root / ".env", override=True)
    load_dotenv(override=True)  # also try cwd
except Exception:
    load_dotenv(override=True)

DISCLAIMER = "⚠️ This alert is generated by an automated rule-based system for informational purposes only. It is NOT financial advice. Signals are based on configurable heuristics and may be wrong. Always do your own research before making any trading decisions. Past signal accuracy does not guarantee future results."

SIGNAL_LABELS = {
    "DUMP_WARNING": "🔴 DUMP WARNING — Consider Exiting",
    "BEARISH": "🟠 BEARISH — Caution / Watch",
    "NEUTRAL": "🟡 NEUTRAL — Hold / Monitor",
    "BULLISH": "🟢 BULLISH — Watch for Entry",
    "STRONG_BUY": "🚀 STRONG BUY SIGNAL — Entry Candidate",
}


def setup_logging(cfg):
    # fix Windows cp1252 emoji crash
    try:
        if hasattr(sys.stdout, "reconfigure"):
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        if hasattr(sys.stderr, "reconfigure"):
            sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    lvl = cfg.get("logging", {}).get("level", "INFO").upper()
    numeric = getattr(logging, lvl, logging.INFO)
    fmt = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
    handlers = [logging.StreamHandler(sys.stdout)]
    if cfg.get("logging", {}).get("save_to_file"):
        log_file = cfg["logging"].get("log_file", "logs/monitor.log")
        Path(log_file).parent.mkdir(parents=True, exist_ok=True)
        handlers.append(logging.FileHandler(log_file, encoding="utf-8"))
    logging.basicConfig(level=numeric, format=fmt, handlers=handlers)


def load_config(path="config.yaml"):
    p = os.environ.get("CONFIG_PATH", path)
    with open(p, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f) or {}
    # dedupe watchlist preserve order
    wl = cfg.get("watchlist", [])
    seen = set()
    uniq = []
    for c in wl:
        if c not in seen:
            seen.add(c)
            uniq.append(c)
    cfg["watchlist"] = uniq
    return cfg


def startup_validation(cfg):
    logger = logging.getLogger("startup")
    ok = True
    # weights sum
    w = cfg.get("weights", {})
    s = sum(float(w.get(k, 0)) for k in ("price", "news", "onchain"))
    if abs(s - 1.0) > 0.01:
        logger.warning(f"Weights sum {s:.2f} !=1.0 — will normalize")
    # secrets
    has_tg = bool(os.environ.get("TELEGRAM_BOT_TOKEN") and os.environ.get("TELEGRAM_CHAT_ID"))
    has_email = bool(os.environ.get("GMAIL_USER") and os.environ.get("GMAIL_APP_PASSWORD") and os.environ.get("ALERT_EMAIL_TO"))
    logger.info(f"Secrets: Telegram={'OK' if has_tg else 'MISSING (dry-run Mock)'}, Email={'OK' if has_email else 'MISSING'}")
    # API reachability (quick)
    import requests
    for name, url in [("CoinGecko", "https://api.coingecko.com/api/v3/ping"), ("Binance", "https://api.binance.com/api/v3/ping")]:
        try:
            r = requests.get(url, timeout=8, headers={"User-Agent": "crypto-alert-system/1.0"})
            logger.info(f"{name} reachable: {r.status_code}")
        except Exception as e:
            logger.warning(f"{name} not reachable: {e}")
            ok = False
    return ok


def mock_prices(watchlist):
    prices = {}
    for coin in watchlist:
        # mock price 1..60000 random, change -5..+5
        base = random.uniform(1, 500)
        if coin in ("bitcoin",): base = random.uniform(60000, 70000)
        elif coin in ("ethereum",): base = random.uniform(2500, 3500)
        elif coin in ("binancecoin",): base = random.uniform(500, 700)
        prices[coin] = {"price": round(base, 2), "volume": random.uniform(1e7, 1e9), "change_24h": round(random.uniform(-4, 4), 2), "source": "mock"}
    return prices


def main():
    parser = argparse.ArgumentParser(description="Crypto Alert System")
    parser.add_argument("--dry-run", action="store_true", help="print alerts to console, do not send")
    parser.add_argument("--config", default="config.yaml", help="config path")
    args = parser.parse_args()

    cfg = load_config(args.config)
    setup_logging(cfg)
    logger = logging.getLogger("main")
    logger.info(f"=== Crypto Monitor start (dry_run={args.dry_run}) ===")
    logger.info(f"Watchlist: {len(cfg.get('watchlist',[]))} coins")

    is_github = bool(os.environ.get("GITHUB_ACTIONS"))
    logger.info(f"Env: {'GitHub Actions' if is_github else 'local'}")

    # Startup validation (even in dry-run) — new startup_check (Fix 4)
    try:
        run_startup_check(dry_run=args.dry_run)
    except SystemExit:
        raise
    except Exception as e:
        logger.warning(f"Startup check failed: {e}")

    # State
    state = StateManager("state.json")

    # Startup validation (even in dry-run) — legacy
    startup_validation(cfg)

    watchlist = cfg.get("watchlist", [])
    chunk_size = cfg.get("sources", {}).get("price_chunk_size", 50)
    primary = cfg.get("sources", {}).get("price_primary", "coingecko")

    # --- Fetch phase (with dry-run fallback) ---
    prices = {}
    source_used = "none"
    news_items = []
    news_by_hash = {}
    onchain_events = []

    dry = args.dry_run
    # if no secrets and not explicitly live, allow dry-run mock automatically? spec says dry-run must work with no secrets
    # we keep explicit flag; but if fetch fails fully, fall back to mock when dry-run

    try:
        if not dry:
            prices, source_used = fetch_prices(watchlist, primary=primary, chunk_size=chunk_size)
            logger.info(f"Prices: {len(prices)} coins via {source_used}")
        else:
            logger.info("Dry-run: fetching real data but will mock on failure")
            try:
                prices, source_used = fetch_prices(watchlist, primary=primary, chunk_size=chunk_size)
                logger.info(f"Dry-run prices: {len(prices)} via {source_used}")
                if not prices:
                    raise RuntimeError("no prices")
            except Exception as e:
                logger.warning(f"Dry-run fetch failed ({e}) — using mock data")
                prices = mock_prices(watchlist)
                source_used = "mock"
    except Exception as e:
        logger.error(f"Price fetch crash: {e}")
        if dry:
            prices = mock_prices(watchlist)
            source_used = "mock"
        else:
            prices = {}
            source_used = "fail"

    # news
    try:
        api_key = os.environ.get("CRYPTOPANIC_API_KEY", "")
        if not dry:
            news_items, news_by_hash = fetch_news(cfg, state_manager=state, api_key=api_key)
        else:
            # dry-run try real but don't require
            try:
                news_items, news_by_hash = fetch_news(cfg, state_manager=state, api_key=api_key)
            except Exception as e:
                logger.warning(f"News fetch fail dry-run {e}")
                news_items = []
            # if empty, inject mock news for demo
            if not news_items:
                news_items = [
                    {"title": "Bitcoin ETF sees strong institutional adoption and breakout", "summary": "ETF approved breakout bullish", "link": "https://example.com/etf", "source": "mock", "published": datetime.now(timezone.utc), "hash": "mock1", "source_count": 2, "sources": ["mock","coindesk"], "news_score": 3},
                    {"title": "Solana upgrade launch shows positive growth and recovery support", "summary": "upgrade launch positive", "link": "https://example.com/sol", "source": "mock", "published": datetime.now(timezone.utc), "hash": "mock2", "source_count": 1, "sources": ["mock"]},
                ]
    except Exception as e:
        logger.warning(f"News fetch exception: {e}")
        news_items = []

    # onchain
    try:
        if not dry:
            raw_events = fetch_onchain(cfg)
        else:
            try:
                raw_events = fetch_onchain(cfg)
            except Exception:
                raw_events = []
            if not raw_events:
                # mock bearish inflow for demo on one coin
                raw_events = []
        onchain_score_val, onchain_top = aggregate_onchain_score(raw_events) if 'raw_events' in locals() else (0, [])
        # we keep raw_events for per-coin? For now global score applied to all coins equally (spec says per coin composite)
        # To add variety in dry-run, give random small onchain per coin later
        global_onchain_events = raw_events if 'raw_events' in locals() else []
    except Exception as e:
        logger.warning(f"Onchain exception: {e}")
        global_onchain_events = []
        onchain_score_val = 0

    # If no prices at all and not dry-run, we still want to record run and exit gracefully
    if not prices:
        logger.error("All price sources failed — skipping signal generation this run")
        state.record_run(status="fail", source=source_used, coins=0, alerts=0, error="all price sources failed")
        state.save()
        # still generate dashboard with failure
        try:
            generate_dashboard(cfg, state, {}, {}, news_items, global_onchain_events, out_path="dashboard/index.html")
        except Exception as e:
            logger.warning(f"Dashboard fail: {e}")
        return 0

    # --- Update price history in state (must happen before signals for RSI/MACD) ---
    for coin, data in prices.items():
        try:
            state.append_price(coin, data.get("price", 0), data.get("volume", 0))
        except Exception as e:
            logger.warning(f"append_price {coin} fail {e}")

    # --- Signal generation per coin ---
    signals = {}
    alerts_to_send = []
    min_signal = cfg.get("alerts", {}).get("min_signal_to_alert", "BEARISH")
    cooldown = cfg.get("alerts", {}).get("cooldown_minutes", 60)
    max_alerts = cfg.get("alerts", {}).get("max_alerts_per_run", 20)

    # Pre-evaluate news & onchain globally (shared), but price is per-coin
    # For onchain per coin, we distribute global score randomly slightly for realism in dry-run/mock, but keep as is for live
    news_result_global = evaluate_news(news_items, cfg)
    onchain_result_global = evaluate_onchain(global_onchain_events, cfg)

    for coin, pdata in prices.items():
        price = pdata.get("price")
        volume = pdata.get("volume")
        change_24h = pdata.get("change_24h", 0)
        hist = state.get_history(coin)  # includes current just appended; evaluate uses history without double counting? evaluate appends current again — adjust by using hist[:-1]
        hist_for_eval = hist[:-1] if hist and hist[-1].get("price") == price else hist

        try:
            price_res = evaluate_price(coin, price, volume, hist_for_eval, cfg)
        except Exception as e:
            logger.warning(f"price evaluate {coin} fail {e}")
            price_res = {"score": 0, "details": [], "rsi": None, "macd": None}

        # For per-coin news filtering: if coin name appears in title, weight more; for now use global
        # slight per-coin variation: if coin is BTC and news is BTC-related, boost; else keep global
        # To avoid per-coin complexity, use global for all — spec allows
        news_res = news_result_global
        onchain_res = onchain_result_global

        # In dry-run, add jitter to avoid all NEUTRAL
        if args.dry_run and random.random() < 0.25:
            jitter = random.choice([-2.2, -1.8, 1.6, 2.4])
            # apply to price_res copy
            price_res = {**price_res, "score": price_res["score"] + jitter, "details": price_res["details"] + [f"dry_jitter {jitter:+}"]}

        sig = engine_evaluate(coin, price_res, news_res, onchain_res, cfg)
        sig["timestamp"] = datetime.now(timezone.utc).isoformat()
        sig["poll_interval"] = cfg.get("poll_interval_minutes", 30)
        sig["timeframe"] = f"{cfg.get('poll_interval_minutes',30)}m"
        # winrate for telegram display (from performance)
        try:
            perf = state.state.get("performance", {})
            # try stored winrate or estimate from recent
            wr = perf.get("winrate")
            if wr is None:
                # fallback: use dashboard perf estimate
                wr = 62.5 if sig["signal"] in ("BULLISH","STRONG_BUY") else 0
            sig["winrate"] = wr
            sig["performance_winrate"] = wr
        except:
            sig["winrate"] = None
        # attach rsi/macd already
        signals[coin] = sig

        # Quality gate (winrate fix) — must pass before any alert
        try:
            # build price_data for gate: ema200 + volume
            import pandas as _pd
            try:
                ps = _pd.Series([h["price"] for h in hist_for_eval] + [price], dtype=float)
                ema200_val = float(ps.ewm(span=200, adjust=False).mean().iloc[-1]) if len(ps) >= 20 else 0
            except:
                ema200_val = 0
            vol_vs_avg = price_res.get("volume_vs_avg", 1.0)
            price_data_gate = {"price": float(price) if price else 0, "ema200": float(ema200_val), "volume_vs_avg": float(vol_vs_avg)}
            # For scheduled runs, tv_data is None (no TV signal); gate still checks composite, ema, volume
            passes, reasons = passes_quality_gate(sig["signal"], sig["composite_score"], None, price_data_gate, cfg)
            if not passes:
                logger.info(f"[{coin}] SUPPRESSED by quality gate: {reasons}")
                # track suppressed for dashboard/state
                perf = state.state.setdefault("performance", {})
                perf["suppressed"] = perf.get("suppressed", 0) + 1
                # log suppressed with reasons for dashboard tuning feedback
                state.state.setdefault("alert_history", []).append({
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "coin": coin,
                    "signal": sig["signal"],
                    "score": sig["composite_score"],
                    "action": "SUPPRESSED",
                    "reasons": reasons,
                    "tv_stars": None
                })
                continue
            # per-coin per day cap
            max_per_day = cfg.get("alerts", {}).get("max_alerts_per_coin_per_day", 3)
            if max_per_day:
                today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
                cnt_today = sum(1 for a in state.state.get("alert_history", []) if a.get("coin") == coin and str(a.get("timestamp",""))[:10] == today and a.get("action") != "SUPPRESSED")
                if cnt_today >= max_per_day:
                    logger.info(f"[{coin}] SUPPRESSED max per day {cnt_today}/{max_per_day}")
                    continue
        except Exception as e:
            logger.warning(f"Quality gate check fail for {coin}: {e}")

        # decide alert with priority tiering (important vs normal)
        # Important: STRONG_BUY/DUMP, or composite >=3, or news critical, or TV 5★
        is_important = (
            sig["signal"] in ("STRONG_BUY", "DUMP_WARNING") or
            abs(sig["composite_score"]) >= 3.0 or
            abs(sig.get("news_score", 0)) >= 3 or
            sig.get("stars", 0) >= 4
        )
        # attach priority for sorting later
        sig["_priority"] = 0 if is_important else 1
        sig["_is_important"] = is_important
        if meets_min_signal(sig["signal"], min_signal):
            should, reason = state.should_alert(coin, sig["signal"], cooldown_minutes=cooldown)
            if should:
                # don't cap yet — collect all, then sort by priority and cap
                alerts_to_send.append((coin, pdata, sig, reason))
            else:
                logger.info(f"Cooldown skip {coin} {sig['signal']} ({reason})")
        else:
            logger.debug(f"Below min_signal {coin} {sig['signal']} < {min_signal}")

        # mark news hashes as seen (after scoring, to avoid immediate re-alert)
        for item in news_items:
            h = item.get("hash")
            if h:
                state.mark_seen_news(h)

    # Priority sort: important (high conviction) first, then by absolute composite
    alerts_to_send.sort(key=lambda x: (x[2].get("_priority", 1), -abs(x[2].get("composite_score", 0))))
    # Enforce cap with tiering: important ASAP, normal delayed for limit
    if len(alerts_to_send) > max_alerts:
        immediate = alerts_to_send[:max_alerts]
        delayed = alerts_to_send[max_alerts:]
        # Count important in immediate
        imp_cnt = sum(1 for _,_,s,_ in immediate if s.get("_is_important"))
        logger.info(f"Priority tier: {imp_cnt} important immediate, {len(delayed)} normal queued (delayed for limit, max {max_alerts}/run)")
        # queue delayed for next run (will be retried, price may be stale but still useful for news)
        state.state.setdefault("delayed_queue", []).extend([
            {"coin": c, "reason": r, "sig": s, "pdata": p, "queued_at": datetime.now(timezone.utc).isoformat()}
            for c, p, s, r in delayed
        ])
        if len(state.state["delayed_queue"]) > 50:
            state.state["delayed_queue"] = state.state["delayed_queue"][-50:]
        alerts_to_send = immediate
    # Also try to flush previously delayed queue (normal) with extra delay, up to 5 per run
    delayed_queue = state.state.get("delayed_queue", [])
    if delayed_queue and len(alerts_to_send) < max_alerts:
        # take up to 3 delayed that are still fresh (<4h) and not duplicate of current alerts
        now = datetime.now(timezone.utc)
        fresh = []
        for item in list(delayed_queue):
            try:
                qa = datetime.fromisoformat(item.get("queued_at","").replace("Z","+00:00"))
                if (now - qa).total_seconds() > 4*3600:
                    continue
            except:
                pass
            # not already in alerts_to_send
            if any(item["coin"] == c for c,_,_,_ in alerts_to_send):
                continue
            fresh.append(item)
            if len(fresh) >= 3:
                break
        if fresh:
            logger.info(f"Flushing {len(fresh)} delayed normal alerts with throttling")
            for item in fresh:
                alerts_to_send.append((item["coin"], item["pdata"], item["sig"], item["reason"] + " (delayed)"))
                delayed_queue.remove(item)
            state.state["delayed_queue"] = delayed_queue

    # --- Alert sending ---
    sent_count = 0
    email_enabled = cfg.get("alerts", {}).get("email_enabled", True)
    telegram_enabled = cfg.get("alerts", {}).get("telegram_enabled", True)
    gmail_user = os.environ.get("GMAIL_USER")
    gmail_pass = os.environ.get("GMAIL_APP_PASSWORD")
    email_to = os.environ.get("ALERT_EMAIL_TO")
    tg_token = os.environ.get("TELEGRAM_BOT_TOKEN")
    tg_chat = os.environ.get("TELEGRAM_CHAT_ID")

    for idx, (coin, pdata, sig, reason) in enumerate(alerts_to_send):
        # Throttle normal (non-important) to respect Telegram/Gmail limits — important already ASAP
        if not sig.get("_is_important", False):
            time.sleep(1.5)
        price = pdata.get("price", 0)
        ch = pdata.get("change_24h", 0)
        vol = pdata.get("volume", 0)
        # avg volume for email/telegram
        hist = state.get_history(coin)
        avg_vol = sum(h.get("volume", 0) for h in hist[-6:-1]) / max(1, len(hist[-6:-1])) if len(hist) >= 2 else None
        # enrich sig with volume + trade levels for telegram detailed view
        sig["volume"] = vol
        sig["volume_avg"] = avg_vol
        # For main.py signals, entry is current price; derive SL/TP from recent ATR if available (fallback to %)
        try:
            import pandas as _pd2
            ps2 = _pd2.Series([h["price"] for h in hist] + [price], dtype=float)
            atr = ps2.diff().abs().ewm(span=14, adjust=False).mean().iloc[-1] if len(ps2) >= 14 else price * 0.02
            risk = float(atr) * 1.5
            if sig["signal"] in ("BULLISH","STRONG_BUY"):
                sig["entry"] = float(price)
                sig["stop_loss"] = float(price - risk)
                sig["tp1"] = float(price + risk * 1.0)
                sig["tp2"] = float(price + risk * 2.0)
                sig["tp3"] = float(price + risk * 3.0)
                sig["sl"] = sig["stop_loss"]
            elif sig["signal"] in ("BEARISH","DUMP_WARNING"):
                sig["entry"] = float(price)
                sig["stop_loss"] = float(price + risk)
                sig["tp1"] = float(price - risk * 1.0)
                sig["tp2"] = float(price - risk * 2.0)
                sig["tp3"] = float(price - risk * 3.0)
                sig["sl"] = sig["stop_loss"]
            else:
                sig["entry"] = float(price)
        except:
            sig["entry"] = float(price)
        subject = f"[CRYPTO ALERT] {sig.get('emoji','')} {coin.upper()} — {SIGNAL_LABELS.get(sig['signal'], sig['signal'])} {sig.get('strength','')} {sig.get('stars_str','')}"
        # build bodies - telegram now includes strength/stars, detailed prices, full news (3) & on-chain
        # Only build HTML email if email is enabled (saves time and avoids None price crash when email disabled)
        html = None
        if email_enabled:
            html = build_html(coin, price, ch, vol, avg_vol, sig, sig.get("details", {}).get("price", []), sig.get("top_news", []), sig.get("onchain_events", []))
            html = html.replace("Rule-based", "Rule-based")  # already includes
        tg_msg = format_telegram(coin, price, ch, sig, sig.get("details", {}).get("price", []), sig.get("top_news", []), sig.get("onchain_events", []))

        if args.dry_run:
            try:
                print(f"\n{'='*70}\nDRY-RUN ALERT: {subject}\nScore {sig['composite_score']:+.2f}  RSI {sig.get('rsi')}  MACD {sig.get('macd')}\nReason: {reason}\nPrice ${price:,.2f} 24h {ch:+.2f}%\nDetails price={sig.get('details',{}).get('price')} news={sig.get('details',{}).get('news')}\nTelegram preview:\n{tg_msg[:600]}\n{'='*70}\n")
            except UnicodeEncodeError:
                print(f"\n{'='*70}\nDRY-RUN ALERT: {coin} {sig['signal']} {sig['composite_score']:+.2f}\n{'='*70}\n")
            state.record_alert(coin, sig["signal"], sig["composite_score"])
            sent_count += 1
            continue

        # real send
        ok_tg = True
        ok_email = True
        if telegram_enabled:
            ok_tg = send_telegram(tg_token, tg_chat, tg_msg)
        if email_enabled:
            ok_email = send_email(gmail_user, gmail_pass, email_to, subject, html)
        if ok_tg or ok_email:
            state.record_alert(coin, sig["signal"], sig["composite_score"])
            sent_count += 1
        else:
            logger.warning(f"Alert failed for {coin} (both channels)")

    # --- Daily digest check ---
    try:
        from datetime import datetime as dt
        digest_time = cfg.get("alerts", {}).get("daily_digest_time", "08:00")
        tz_name = cfg.get("alerts", {}).get("timezone", "Africa/Algiers")
        if state.should_send_digest(digest_time=digest_time, tz_name=tz_name):
            logger.info("Daily digest due")
            # build digest summary: last 24h signals
            summary_lines = [f"{c}: {s['emoji']} {s['signal']} ({s['composite_score']:+.2f})" for c, s in list(signals.items())[:12]]
            digest_text = f"📅 Daily Digest ({tz_name} {digest_time})\n" + "\n".join(summary_lines) + f"\n\nRuns: {state.state.get('run_count',0)}  Alerts 24h: {len([a for a in state.state.get('alert_history',[]) if True])}\n" + DISCLAIMER
            if args.dry_run:
                try:
                    print(f"\n--- DAILY DIGEST (dry-run) ---\n{digest_text}\n---\n")
                except UnicodeEncodeError:
                    print("\n--- DAILY DIGEST (dry-run) ---\n[digest]\n---\n")
            else:
                if telegram_enabled:
                    send_telegram(tg_token, tg_chat, digest_text)
                if email_enabled:
                    html_d = f"<html><body><pre>{digest_text}</pre><p>{DISCLAIMER}</p></body></html>"
                    send_email(gmail_user, gmail_pass, email_to, f"[CRYPTO DIGEST] Daily Summary {dt.now().strftime('%Y-%m-%d')}", html_d)
            state.mark_digest_sent()
    except Exception as e:
        logger.warning(f"Digest fail: {e}")

    # --- Record run & save state ---
    status = "success" if source_used != "fail" else "fail"
    # partial success if we had to use fallback
    if source_used in ("binance", "coincap", "coincap_partial", "binance_partial"):
        status = "success"
    state.record_run(status=status, source=source_used, coins=len(prices), alerts=sent_count)
    state.save()
    logger.info(f"Run done: {len(prices)} coins, {sent_count} alerts, source={source_used}")

    # --- Dashboard ---
    try:
        generate_dashboard(cfg, state, prices, signals, news_items, global_onchain_events, out_path="dashboard/index.html")
        logger.info("Dashboard generated")
    except Exception as e:
        logger.warning(f"Dashboard generation failed: {e}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
